// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaReservaSalas.Data;

#nullable disable

namespace SistemaReservaSalas.Migrations
{
    [DbContext(typeof(SalaDbContext))]
    partial class SalaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("SistemaReservaSalas.Data.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sala");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Capacidade = 10,
                            Descricao = "Sala de aula",
                            Nome = "Sala 1"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Capacidade = 20,
                            Descricao = "Sala de aula",
                            Nome = "Sala 2"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Capacidade = 20,
                            Descricao = "Laboratório de computação",
                            Nome = "Lab Comp 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
